@startuml
title 구매 API 시퀀스 다이어그램

actor 사용자 as User
participant "ApiProductController" as Controller
participant "ProductService" as ProductService
participant "ProductMapper" as ProductMapper
participant "OrderService" as OrderService
participant "Order" as Order
participant "OrderMapper" as OrderMapper
database "Database" as DB


User -> Controller : POST /api/products/{productId}/purchase(request)
activate Controller

Controller -> ProductService : reduceStock(request)
activate ProductService

note right of ProductService : 트랜잭션 시작
    ProductService -> ProductMapper : getProductById(id)
    activate ProductMapper
        ProductMapper -> DB : getProductById(id)
        activate DB
        DB --> ProductMapper : Product
        deactivate DB
    ProductMapper --> ProductService : Product
    deactivate ProductMapper

    opt product == null
    ProductService --> Controller : ProductNotFoundException
    note right of ProductService : 예외 발생으로 인한 트랜잭션 종료
    end
    opt product.stock < reqeust.quantity
    ProductService --> Controller : OutOfStockException
    note right of ProductService : 예외 발생으로 인한 트랜잭션 종료
    end

    ProductService -> ProductService : product.setStock(stock - quantity)
    ProductService -> ProductMapper : updateProductStock(product)
    ProductMapper -> DB : updateProduct(product)
    ProductService -> OrderService : addOrder(id)
    activate OrderService
        OrderService -> Order : new Order()
        activate Order
        Order --> OrderService : order
        deactivate Order
        OrderService -> OrderService : order.setProductId(id)
        OrderService -> OrderService : order.setOrderDate(LocalDateTime.now());
        deactivate Order
    OrderService -> OrderMapper : insertOrder(order)
    OrderMapper -> DB : insertOrder(order)

    opt order.id == 0
    OrderService --> Controller : OrderNotFoundException
    note right of ProductService : 예외 발생으로 인한 트랜잭션 종료
    end
    deactivate OrderService
    deactivate ProductService
    note right of ProductService : 트랜잭션 종료

Controller --> User : 구매가 완료되었습니다.
deactivate Controller

@enduml