@startuml
title 구매 API 시퀀스 다이어그램

actor 사용자 as User
participant "ApiProductController" as Controller
participant "PurchaseService" as PurchaseService
participant "ProductService" as ProductService
participant "ProductMapper" as ProductMapper
participant "OrderService" as OrderService
participant "OrderMapper" as OrderMapper


User -> Controller : POST /api/products/{productId}/purchase(request)
activate Controller


Controller -> PurchaseService : purchase(productId)
note right of PurchaseService : 트랜잭션 시작
activate PurchaseService

PurchaseService -> ProductService : reduceStock(productId, 1)
activate ProductService

note right of ProductService : 배타 락 획득
ProductService -> ProductMapper : getProductByIdForUpdate(productId)
activate ProductMapper
ProductMapper --> ProductService : Product
deactivate ProductMapper

opt product.stock < quantity
ProductService --> Controller : OutOfStockException
end

ProductService -> ProductService : product.setStock(product.getStock() - quantity)
ProductService -> ProductMapper : updateProductStock(product.getId(), product.getStock())
activate ProductMapper
ProductMapper --> ProductService :
deactivate ProductMapper

ProductService --> PurchaseService
deactivate ProductService

PurchaseService -> OrderService : makeOrder(productId)
activate OrderService
OrderService -> OrderMapper : insertOrder(order)
activate OrderMapper
OrderMapper --> OrderService
deactivate OrderMapper
OrderService --> PurchaseService : Order
deactivate OrderService

PurchaseService --> Controller : Order
deactivate PurchaseService
note right of PurchaseService : 배타 락 반납\n트랜잭션 종료

Controller --> User : 구매가 완료되었습니다.
deactivate Controller

@enduml